# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statistictypes', '0001_initial'),
        ('games', '0004_auto_20170105_1518'),
        ('players', '0005_player_known_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='statistic_value')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_for_playerstats', to='games.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_for_playerstats', to='players.Player')),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_for_playerstats', to='statistictypes.StatisticType')),
            ],
        ),
    ]
