# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerstatistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistic',
            name='value',
            field=models.FloatField(default=0.0, verbose_name='value'),
        ),
    ]
