# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistictypes', '0001_initial'),
        ('games', '0004_auto_20170105_1518'),
        ('players', '0005_player_known_name'),
        ('playerstatistics', '0002_auto_20170107_1826'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerstatistic',
            unique_together=set([('game', 'player', 'statistic')]),
        ),
    ]
