# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventstatistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.BigIntegerField(unique=True)),
                ('qualifier_id', models.IntegerField()),
                ('value', models.CharField(default=None, max_length=500, null=True, verbose_name='Value')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_for_qualifier', to='eventstatistics.EventStatistic')),
            ],
        ),
    ]
