# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualifiers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualifier',
            old_name='event',
            new_name='event_statistic',
        ),
    ]
