# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
