# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
