# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True, verbose_name='Opta uID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Birth Place')),
                ('nationality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nationality')),
                ('weight', models.FloatField(default=0.0, verbose_name='Weight')),
                ('height', models.FloatField(default=0.0, verbose_name='Height')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Real Position')),
                ('position_side', models.CharField(blank=True, max_length=255, null=True, verbose_name='Real Position Side')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
            ],
        ),
    ]
