# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw_id', models.IntegerField(verbose_name='SW_Analytics_ID')),
                ('opta_statistic_type_name', models.CharField(max_length=350, verbose_name='Stat_type_name')),
                ('opta_statistic_definition', models.CharField(max_length=350, verbose_name='Definition')),
            ],
        ),
    ]
