# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistictypes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistictype',
            name='id',
        ),
        migrations.AlterField(
            model_name='statistictype',
            name='opta_statistic_type_name',
            field=models.CharField(max_length=350, primary_key=True, serialize=False, verbose_name='Stat_type_name'),
        ),
    ]
