# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0005_player_known_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(verbose_name='Season')),
                ('base_salary', models.FloatField(default=0.0, null=True, verbose_name='Base Salary ($)')),
                ('compensation', models.FloatField(default=0.0, null=True, verbose_name='Total Compensation ($)')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_tied_to_salary', to='players.Player')),
            ],
        ),
    ]
