# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_auto_20161231_2117'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True, verbose_name='Opta uID')),
                ('date', models.DateField(verbose_name='Date Played')),
                ('attendance', models.IntegerField(blank=True, null=True, verbose_name='Attendance')),
                ('first_half_time', models.IntegerField(verbose_name='1st Half Length (mins)')),
                ('second_half_time', models.IntegerField(verbose_name='2nd Half Length (mins)')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_away_team', to='teams.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_home_team', to='teams.Team')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_venue', to='venues.Venue')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_winner', to='teams.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('home_team', 'away_team', 'date')]),
        ),
    ]
