# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20170105_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team_score',
            field=models.IntegerField(null=True, verbose_name='Final Score of Away Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_score',
            field=models.IntegerField(null=True, verbose_name='Final Score of Home Team'),
        ),
    ]
