# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statistictypes', '0001_initial'),
        ('teams', '0002_auto_20161231_2117'),
        ('games', '0004_auto_20170105_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_half_value', models.IntegerField(default=0, verbose_name='1H Value')),
                ('second_half_value', models.IntegerField(default=0, verbose_name='2H Value')),
                ('extra_time_first_half_value', models.IntegerField(null=True, verbose_name='ET1H Value')),
                ('extra_time_second_half_value', models.IntegerField(null=True, verbose_name='ET2H Value')),
                ('full_time_value', models.IntegerField(default=0, verbose_name='FT Value')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_for_teamstats', to='games.Game')),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_for_teamstats', to='statistictypes.StatisticType')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_for_teamstats', to='teams.Team')),
            ],
        ),
    ]
