# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamstatistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamstatistic',
            old_name='full_time_value',
            new_name='FT_value',
        ),
        migrations.RemoveField(
            model_name='teamstatistic',
            name='extra_time_first_half_value',
        ),
        migrations.RemoveField(
            model_name='teamstatistic',
            name='extra_time_second_half_value',
        ),
        migrations.RemoveField(
            model_name='teamstatistic',
            name='first_half_value',
        ),
        migrations.RemoveField(
            model_name='teamstatistic',
            name='second_half_value',
        ),
        migrations.AddField(
            model_name='teamstatistic',
            name='ETFH_value',
            field=models.IntegerField(null=True, verbose_name='ETFH Value'),
        ),
        migrations.AddField(
            model_name='teamstatistic',
            name='ETSH_value',
            field=models.IntegerField(null=True, verbose_name='ETSH Value'),
        ),
        migrations.AddField(
            model_name='teamstatistic',
            name='FH_value',
            field=models.IntegerField(default=0, verbose_name='FH Value'),
        ),
        migrations.AddField(
            model_name='teamstatistic',
            name='SH_value',
            field=models.IntegerField(default=0, verbose_name='SH Value'),
        ),
    ]
