# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamstatistics', '0002_auto_20170107_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstatistic',
            name='ETFH_value',
            field=models.FloatField(null=True, verbose_name='ETFH Value'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='ETSH_value',
            field=models.FloatField(null=True, verbose_name='ETSH Value'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='FH_value',
            field=models.FloatField(default=0.0, verbose_name='FH Value'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='FT_value',
            field=models.FloatField(default=0.0, verbose_name='FT Value'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='SH_value',
            field=models.FloatField(default=0.0, verbose_name='SH Value'),
        ),
    ]
