# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamstatistics', '0003_auto_20170107_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstatistic',
            name='FT_value',
        ),
        migrations.AddField(
            model_name='teamstatistic',
            name='value',
            field=models.FloatField(default=0.0, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='FH_value',
            field=models.FloatField(default=0.0, null=True, verbose_name='FH Value'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='SH_value',
            field=models.FloatField(default=0.0, null=True, verbose_name='SH Value'),
        ),
    ]
