# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20161231_2117'),
        ('statistictypes', '0001_initial'),
        ('games', '0004_auto_20170105_1518'),
        ('teamstatistics', '0004_auto_20170107_1850'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamstatistic',
            unique_together=set([('game', 'team', 'statistic')]),
        ),
    ]
