# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_auto_20161231_2117'),
        ('games', '0004_auto_20170105_1518'),
        ('players', '0005_player_known_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_formation', models.CharField(max_length=25)),
                ('player_position', models.CharField(max_length=255)),
                ('player_subposition', models.CharField(max_length=255, null=True)),
                ('is_captain', models.BooleanField(default=False)),
                ('player_formation_number', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_for_lineup', to='games.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_for_lineup', to='players.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_for_lineup', to='teams.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lineup',
            unique_together=set([('game', 'player')]),
        ),
    ]
