# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='player_formation_number',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=0),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='player_position',
            field=models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Wing Back', 'Wing Back'), ('Full Back', 'Full Back'), ('Defender', 'Defender'), ('Central Defender', 'Central Defender'), ('Defensive Midfielder', 'Defensive Midfielder'), ('Attacking Midfielder', 'Attacking Midfielder'), ('Central Midfielder', 'Central Midfielder'), ('Midfielder', 'Midfielder'), ('Winger', 'Winger'), ('Striker', 'Striker'), ('Second Striker', 'Second Striker'), ('Substitute', 'Substitute')], max_length=255),
        ),
    ]
