# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_auto_20161231_2117'),
        ('games', '0004_auto_20170105_1518'),
        ('players', '0005_player_known_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.BigIntegerField(unique=True, verbose_name='Opta Unique ID')),
                ('event_id', models.IntegerField(verbose_name='Unique ID within a game')),
                ('type_id', models.IntegerField(verbose_name='type of event')),
                ('period_id', models.IntegerField()),
                ('minute', models.IntegerField(verbose_name='Game time minute')),
                ('second', models.IntegerField(verbose_name='Game time second')),
                ('outcome', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('assist', models.BooleanField(default=False)),
                ('keypass', models.BooleanField(default=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_of_event', to='games.Game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_of_event', to='players.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_of_event', to='teams.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eventstatistic',
            unique_together=set([('game', 'event_id')]),
        ),
    ]
