# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventstatistics', '0003_auto_20170112_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventstatistic',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='eventstatistic',
            name='relative_time',
            field=models.FloatField(default=-999999, verbose_name='Relative Seconds of Event'),
        ),
    ]
