# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventstatistics', '0006_remove_eventstatistic_relative_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatistic',
            name='relative_seconds',
            field=models.FloatField(default=-999999, verbose_name='Relative Seconds of Event'),
        ),
    ]
