# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20161231_2117'),
        ('games', '0004_auto_20170105_1518'),
        ('eventstatistics', '0007_eventstatistic_relative_seconds'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventstatistic',
            unique_together=set([('game', 'team', 'event_id', 'type_id')]),
        ),
    ]
