# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventstatistics', '0008_auto_20170113_0633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstatistic',
            options={'ordering': ['period_id', 'minute', 'second', 'relative_seconds']},
        ),
    ]
